dependencies:
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.4.0
  color_tft:
    url: github.com/toitware/toit-color-tft
    version: ^1.3.0
  font_x11_adobe:
    url: github.com/toitlang/pkg-font-x11-adobe
    version: ^0.1.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.9.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.3.0
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.2.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  pictogrammers_icons:
    url: github.com/toitware/toit-icons-pictogrammers
    version: ^1.0.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.6.0
  png_display:
    url: github.com/toitware/toit-png-display.git
    version: ^0.2.0
